# MT25XXX

CC=gcc
CFLAGS=-O2 -pthread

all:
	$(CC) $(CFLAGS) MT25009_Part_A1_Server.c -o A1S
	$(CC) $(CFLAGS) MT25009_Part_A1_Client.c -o A1C
	$(CC) $(CFLAGS) MT25009_Part_A2_Server.c -o A2S
	$(CC) $(CFLAGS) MT25009_Part_A2_Client.c -o A2C
	$(CC) $(CFLAGS) MT25009_Part_A3_Server.c -o A3S
	$(CC) $(CFLAGS) MT25009_Part_A3_Client.c -o A3C
